### ISSUE TITLE
Pip Install Import issue

### ISSUE THREAD

**Issue by Jamian** [jmons/ramlwrap#5]
Trying to pip install for the first time and hitting an import issue when running Django.

```
  File "/home/bla/bla/bla/bla/venv/lib/python3.5/site-packages/ramlwrap/__init__.py", line 1, in <module>
    from RamlWrap import ramlwrap
ImportError: No module named 'RamlWrap'
```

**Comment by Jamian** [comment]
Check out https://github.com/jmons/ramlwrap/pull/6 to see this fix

**Comment by jmons** [comment]
You seem to have fixed it with that pragmatic use of punctuation. +1
