### ISSUE TITLE
Review dependancies

### ISSUE THREAD

**Issue by jmons** [jmons/ramlwrap#8]
It's possible there are some dependencies which could be removed - especially RestAPI ?

**Comment by Jamian** [comment]
As if, we need them all.... but....

We could do some refactoring to remove the need for the djangorestframework - looks to me like it's only being used [here](https://github.com/jmons/ramlwrap/blob/master/ramlwrap/utils/validation.py#L4#L5).

**Comment by jmons** [comment]
I think quite minor - they're only used for thost POST / GET decorators, and thats a simple 'if POST' or 'if GET' added in.

I also think we should be able to change things like the django dependancy back to like 1. uhh 2? (and possibly beyond - although Im not sure when this style of urlpatterns was done...). I might make a quick unit test rig to test this in different django versions before trying that though.

When it comes to major refactoring i do want to move away from the pyraml parser and onto just using pyyaml and doing our own parsing to enable us to work with raml1.0 independantly (as we dont need a fully compliant raml parser - most of the raml options I guess we don't care about).

Somewhere we should state this only works with single argument json-body requests at the moment not all the argument stuff (and possibly only with Json schema not the raml objecty stuff either).

**Comment by jmons** [comment]
I went through some careful dependancy testing on the django versions: 
<img width="341" alt="screen shot 2017-03-28 at 22 54 39" src="https://cloud.githubusercontent.com/assets/459533/24429821/a1ffcfcc-140b-11e7-824a-a86b8a42591a.png">

Basically, looking at the Django supported versions, Django community only supports 1.8 as LTS, and nothing before that: 
![release-roadmap e844db08610e](https://cloud.githubusercontent.com/assets/459533/24429866/cb7297f4-140b-11e7-8629-32ae2fd94049.png)

I've set the minimum version in the setup.py to 1.7 though as it does work on this version, but running earlier then this causes some issues as Django itself isn't python3 compatible before 1.7. (in theory it seems to work all the way back to Django 1.3 ish, and I can probably get it to work back on 0.9x as well, but I don't think anyone cares, or if they do, they're not the people who will be using this lib*.)

I'm going to close this issue now though, as we've removed the testing requirements into the dev dependancies, and we've got a good range of other software versions, I think.

* _please someone correct me, because that means we have a wide range of users._

**Comment by jmons** [comment]
Closing, as per #22 contains a better minimal dependancy requirements.
